version: 2

models:
  - name: int_orders_consolidated_ayahany
    description: "Intermediate model consolidating order-level metrics"
    columns:
      - name: order_id
        description: "Primary key for the consolidated order model"
        tests:
          - unique
          - not_null